### ISSUE TITLE
Question about the results

### ISSUE THREAD

**Issue by yassouali** [gatheluck/FourierHeatmap#1]
First of all, thank you very much for this implementation, I had some troubles when trying to implement Fourier heatmaps on my own.

I used `AddFourierNoise` on my own dataset/model following eval.py, but the error is the same across all frequencies, do you have an idea on the possible problem?

![image](https://user-images.githubusercontent.com/45082182/83777203-701e8480-a689-11ea-9277-3a832099f499.png)
![image](https://user-images.githubusercontent.com/45082182/83777248-7ad91980-a689-11ea-96f2-fc82c47aac76.png)

Thanks

**Comment by yassouali** [comment]
I missed an important step, noise needs to added before normalization. Things are working now, thank you!

**Comment by karthikramesh55** [comment]
Hello @yassouali,

Just had a few queries regarding the concepts discussed in the paper that I found hard to understand, and wondered if you could kindly help me with them:

1. What exactly is "frequency information" of the corruptions that the authors refer to, when we deal with image datasets and classification models?

2. How is the Fourier heatmap generated, given an image dataset and a model? I looked at the codebase on GitHub (as mentioned on Page 1 of the paper) and was struggling a bit with grasping as to what was going on.

3. How do we interpret a Fourier heatmap that is generated for a given image dataset and a classification model? What do the different colors mean in the spectral legend of the heatmap?

Thanks in advance.

**Comment by yassouali** [comment]
Hi @karthikramesh55 

It is been some time since I've read the paper, so take my answers with a grain of salt :)

The frequency information of an image is simply how the frequencies of an image are distributed into low & high frequencies, and for natural images that depict real-world objects, there is a lot more low-frequency information (more semantically meaningful, like the shape) than high-frequency information (like edges/borders). Now, for a given corruption, we can either chose to corrupt low or high-frequencies, targeting different sources of information in the images, and for classification, you can imagine that the low frequencies are far more indicative of the object type, so if we remove them, the accuracy drops.

In the heat map, each cell corresponds to a given perturbation applied to the input image, which is then passed through the trained model to get the prediction error, and the color of the cell is the error obtained (note that we use N images for more stable results). The center of the heat map corresponds to low-frequency noise, and to father, you go from the center the higher the frequency of the noise. As for how the noise is added, for each cell in the heap map/type of corruption, we construct a Fourier basis, and apply an inverse DFT to gen an additive noise in the image space, had finally add it to our input image (note the noise is only created once and reused for all images)

See the implementation in the repo [here](https://github.com/gatheluck/FourierHeatmap/tree/master/fhmap/fourier), it is maybe more clear the authors.

**Comment by karthikramesh55** [comment]
Hello @yassouali 

Thanks a ton for your response. The concepts are clear now.

Best regards,
Karthik
